### ISSUE TITLE
When ingesting metadata templates and DAs, to use GSP to insert content into the triplestore instead of multiple queries.

### ISSUE THREAD

**Issue by paulopinheiro1234** [HADatAc/hascoapi#20]

**Comment by NaelQuin** [comment]
The ingestion process is **3x faster**.

**Comment by NaelQuin** [comment]
Ignoring the `deleteFromTripleStore()` process, in `HADatAcThing.saveToTripleStore()` method, we can make the process of ingesting each HADatAcThing take about seconds.
